name: Windows Build Boost Fetch

on:
  push:
    branches: [ master, fix_windows_ci ]
    paths:
      - ".github/workflows/windows_build_no_boost.yml"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/windows_build_no_boost.yml"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"

jobs:
  build:
    runs-on: windows-2022
    env:
      CMAKE_PREFIX_PATH: ${{ github.workspace }}\.local
    steps:
    - uses: actions/checkout@v2
    
    - name: Install OpenSSL
      run: choco install openssl.light

    - name: Get GitHub SSL certificate
      run: |
        echo | openssl s_client -servername github.com -connect github.com:443 2>/dev/null | openssl x509 > github.crt

    - name: Add GitHub SSL certificate to trusted store
      run: |
        certutil -addstore -f "Root" github.crt

    - name: Configure CMake
      run: cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DQUICK_FTXUI_FETCH_BOOST=ON
        
    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Test
      run: |
        cd build
        ctest -C Release
    - name: Install
      run: cmake --install build --config Release --prefix "$env:CMAKE_PREFIX_PATH"
